### ISSUE TITLE
Sports Page Testing 2

### ISSUE THREAD

**Issue by JoshBrink** [COSC481W-2021Winter/capstone-project-athletisize-1#29]

**Comment by etracht** [comment]
### EMILY
**Nav Bar Link Tests**
- [x] Home
- [x] Sports
- [x] About
- [x] Contact
- [x] Log In
- [x] Sign Up

**Sport page link test**
- [x] Baseball/Softball
- [x] Hockey
- [x] Lacrosse
- [x] Ski
- [x] Snowboard
- [x] Soccer

### YAOZE
**Image Test**
- [x] Logo

**Pdf Links**
- [x] Baseball/Softball pdf link
- [x] Hockey pdf link
- [x] Lacrosse pdf link
- [x] Ski pdf link
- [x] Snowboard pdf link
- [x] Soccer pdf link
