### ISSUE TITLE
About Us Testing 2

### ISSUE THREAD

**Issue by JoshBrink** [COSC481W-2021Winter/capstone-project-athletisize-1#30]

**Comment by JonathanNemchak** [comment]
Header

- [ ] Logo picture

Nav Bar

- [ ] Home
- [ ] About
- [ ] Contact
- [ ] Sports
- [ ] Login
- [ ] Sign up

Body

- [ ] Meet the Team
- [ ] Team description

- [ ] Josh Picture
     - [ ] Github button
     - [ ] LinkedIn button
- [ ] Emily Picture
     - [ ] Github button
     - [ ] LinkedIn button
- [ ] Yaoze Picture
     - [ ] Github button
     - [ ] LinkedIn button
- [ ] Dylan Picture
     - [ ] Github button
     - [ ] LinkedIn button
- [ ] Jonathan Picture
     - [ ] Github button
     - [ ] LinkedIn button
- [ ] Ali Picture
     - [ ] Github button
     - [ ] LinkedIn button
- [ ] Rahmah Picture
     - [ ] Github button
     - [ ] LinkedIn button
- [ ] Michael Picture
