### ISSUE TITLE
Add tabs and information to get started modal

### ISSUE THREAD

**Issue by JoshBrink** [COSC481W-2021Winter/capstone-project-athletisize-1#62]
- [ ] Add tabs to get started modal
- [ ] Create checked (or radial) forms on each tab
- [ ] Fill in information on each form

**Comment by sjiang1** [comment]
For all the sports (Hockey, Soccer, Lacrosse, Baseball, Downhill Ski, and Snowboard), the choose sport tab and the equipment tab will be finished. That means: if the user choose a sport, the equipment tab should show the corresponding equipments for that sport. So the user should be able to select equipments on the equipments tab (the user can select multiple equipments.) 

The measurements tab will only show a form shell (and the user will not be able to put measurements in the tab.)
The results tab will not be finished.
