### ISSUE TITLE
Create dummy email and connect contact us form

### ISSUE THREAD

**Issue by JoshBrink** [COSC481W-2021Winter/capstone-project-athletisize-1#63]
- [x] Create dummy email (athletisize@gmail.com)
- [x] Connect Contact Us form to dummy email

**Comment by sjiang1** [comment]
You will be able to fill the contact us form on the website and submit. With the submission, an email will be sent to athletisize@gmail.com

This should work on everyone's machine (so as the instructor, I can run the website and check if the email will be sent.)
